@baseUrl = https://localhost:7108

###
GET {{baseUrl}}/login

###
GET {{baseUrl}}/logout

###
GET {{baseUrl}}/user

###
GET {{baseUrl}}/secure

###
GET {{baseUrl}}/supervisor-only

###
GET {{baseUrl}}/admin-only

###
POST {{baseUrl}}/drive/bus