@baseURL = https://localhost:7281
@productId = 2779ee47-10b0-4bd7-8342-404006aa1392

### Old route
GET {{baseURL}}/api/products/{{productId}}

### V1 route with url versioning
GET {{baseURL}}/api/v1/products/{{productId}}

### V2 route with url versioning
GET {{baseURL}}/api/v2/products/{{productId}}

### V1 route with query string versioning
GET {{baseURL}}/api/products/{{productId}}?api-version=1.0

### V2 route with qeury string versioning
GET {{baseURL}}/api/products/{{productId}}?api-version=2.0

### V1 route with header versioning
GET {{baseURL}}/api/products/{{productId}}
api-version: 1.0

### V2 route with header versioning
GET {{baseURL}}/api/products/{{productId}}
api-version: 2.0

### V1 route with media type versioning
GET {{baseURL}}/api/products/{{productId}}
Accept: application/json; v=1.0

### V2 route with media type versioning
GET {{baseURL}}/api/products/{{productId}}
Accept: application/json; v=2.0